"""BGKit-format compressed spans generated by the decoder (restart plan 3.2, stage B2).

A span is ``<|bg|>(rho) r_1 ... r_k <|/bg|>``: a marker whose input embedding is a
learned vector plus a zero-initialized MLP of Fourier features of log2(rho), then k
representation vectors in the decoder's input-embedding space, each produced by
the rep head from the previous position's final hidden state and fed back as the
next input, then a stop. Inside a span the only choice of the ordinary head is
``<|rep|>`` against ``<|/bg|>``; during B2 (decoder frozen) that choice is a
two-row head whose rows later become those tokens' output rows.

Pure torch, so the core tests need no BGKit checkout or downloads.
"""
from __future__ import annotations

import math

import torch
from torch import nn

# Write prompts placed before the span (owner direction, 27 September). They name
# the BGKit format. Pipeline (knowledge-base) writes ask for BGKit compaction of the
# passage into a memory record, so the frozen early stages start from states aimed
# at a recallable record; classical BGKit compression (reconstruct / continue on
# BGKit's corpus, any ratio x1-x128) is phrased as "summarize with BGKit", keeping
# compressed output a general, prompted skill.
MEMORY_PROMPT = ('Compact the following passage with BGKit into a memory record, so that '
                 'its content can later be recalled and reproduced verbatim.\n\n')
SUMMARIZE_PROMPTS = {
    'reconstruct': 'Summarize this text with BGKit so that it can be reproduced verbatim.\n\n',
    'continue': 'Summarize this text with BGKit so that it can be continued.\n\n',
}


class RatioEmbedding(nn.Module):
    """Continuous compression-ratio code: MLP of Fourier features of log2(rho).

    The output layer is zero-initialized, so at step 0 the marker embedding is
    the plain learned vector for every ratio."""

    def __init__(self, width: int, frequencies: int = 8, hidden: int = 256):
        super().__init__()
        self.register_buffer('scales', 2.0 ** torch.arange(frequencies) * (math.pi / 8),
                             persistent=False)
        self.net = nn.Sequential(nn.Linear(2 * frequencies + 1, hidden), nn.SiLU(),
                                 nn.Linear(hidden, width))
        nn.init.zeros_(self.net[-1].weight)
        nn.init.zeros_(self.net[-1].bias)

    def forward(self, factor: torch.Tensor) -> torch.Tensor:
        x = torch.log2(factor.float()).unsqueeze(-1)
        angles = x * self.scales
        return self.net(torch.cat([x / 8, angles.sin(), angles.cos()], dim=-1))


def interface_rms(x: torch.Tensor, target_norm: float) -> torch.Tensor:
    """BGKit S2's rms-only DecoderInterfaceNorm: rows rescaled to norm ``target_norm``."""
    eps = 0.05 * target_norm
    return x / (x.norm(dim=-1, keepdim=True) + eps) * target_norm


class RepHead(nn.Module):
    """Final hidden state -> next representation, in decoder input-embedding space."""

    def __init__(self, width: int, target_norm: float, hidden: int | None = None):
        super().__init__()
        hidden = hidden or 2 * width
        self.target_norm = float(target_norm)
        self.net = nn.Sequential(nn.LayerNorm(width), nn.Linear(width, hidden), nn.SiLU(),
                                 nn.Linear(hidden, width))

    def forward(self, hidden: torch.Tensor) -> torch.Tensor:
        return interface_rms(self.net(hidden.float()), self.target_norm)


class SpanWriter(nn.Module):
    """Trainable write-side parts of B2: marker, ratio code, rep head, stop head."""

    def __init__(self, width: int, target_norm: float, marker_init: torch.Tensor | None = None):
        super().__init__()
        marker = torch.zeros(width) if marker_init is None else marker_init.detach().float().clone()
        self.marker = nn.Parameter(marker)
        self.ratio = RatioEmbedding(width)
        self.rep = RepHead(width, target_norm)
        self.stop = nn.Linear(width, 2)  # logits over (<|rep|>, <|/bg|>)

    def marker_embedding(self, factor: torch.Tensor) -> torch.Tensor:
        return self.marker + self.ratio(factor)


def span_targets(counts: list[int], device=None) -> torch.Tensor:
    """Stop labels for spans of ``counts`` reps: k positions of 0 (emit), then 1 (stop).

    Returned flat, in the order of the positions marker, r_1 ... r_k per span."""
    labels = []
    for k in counts:
        labels.extend([0] * k + [1])
    return torch.tensor(labels, dtype=torch.long, device=device)
