"""BGKit-format compressed spans generated by the decoder (restart plan 3.2, stage B2).

A span is ``<|bg|>(rho) r_1 ... r_k <|/bg|>``: a marker whose input embedding is a
learned vector plus a zero-initialized MLP of Fourier features of log2(rho), then k
representation vectors in the decoder's input-embedding space, each produced by
the rep head from the previous position's final hidden state and fed back as the
next input, then a stop. Inside a span the only choice of the ordinary head is
``<|rep|>`` against ``<|/bg|>``; during B2 (decoder frozen) that choice is a
two-row head whose rows later become those tokens' output rows.

Pure torch, so the core tests need no BGKit checkout or downloads.
"""
from __future__ import annotations

import math

import torch
from torch import nn

# Write prompts placed before the span (owner direction, 27 September). They name
# the BGKit format. Pipeline (knowledge-base) writes ask for BGKit compaction of the
# passage into a memory record, so the frozen early stages start from states aimed
# at a recallable record; classical BGKit compression (reconstruct / continue on
# BGKit's corpus, any ratio x1-x128) is phrased as "summarize with BGKit", keeping
# compressed output a general, prompted skill.
MEMORY_PROMPT = ('Compact the following passage with BGKit into a memory record, so that '
                 'its content can later be recalled and reproduced verbatim.\n\n')
SUMMARIZE_PROMPTS = {
    'reconstruct': 'Summarize this text with BGKit so that it can be reproduced verbatim.\n\n',
    'continue': 'Summarize this text with BGKit so that it can be continued.\n\n',
}


class RatioEmbedding(nn.Module):
    """Continuous compression-ratio code: MLP of Fourier features of log2(rho).

    The output layer is zero-initialized, so at step 0 the marker embedding is
    the plain learned vector for every ratio."""

    def __init__(self, width: int, frequencies: int = 8, hidden: int = 256):
        super().__init__()
        self.register_buffer('scales', 2.0 ** torch.arange(frequencies) * (math.pi / 8),
                             persistent=False)
        self.net = nn.Sequential(nn.Linear(2 * frequencies + 1, hidden), nn.SiLU(),
                                 nn.Linear(hidden, width))
        nn.init.zeros_(self.net[-1].weight)
        nn.init.zeros_(self.net[-1].bias)

    def forward(self, factor: torch.Tensor) -> torch.Tensor:
        x = torch.log2(factor.float()).unsqueeze(-1)
        angles = x * self.scales
        return self.net(torch.cat([x / 8, angles.sin(), angles.cos()], dim=-1))


def interface_rms(x: torch.Tensor, target_norm: float) -> torch.Tensor:
    """BGKit S2's rms-only DecoderInterfaceNorm: rows rescaled to norm ``target_norm``."""
    eps = 0.05 * target_norm
    return x / (x.norm(dim=-1, keepdim=True) + eps) * target_norm


class RepHead(nn.Module):
    """Final hidden state -> next representation, in decoder input-embedding space."""

    def __init__(self, width: int, target_norm: float, hidden: int | None = None):
        super().__init__()
        hidden = hidden or 2 * width
        self.target_norm = float(target_norm)
        self.net = nn.Sequential(nn.LayerNorm(width), nn.Linear(width, hidden), nn.SiLU(),
                                 nn.Linear(hidden, width))

    def forward(self, hidden: torch.Tensor) -> torch.Tensor:
        return interface_rms(self.net(hidden.float()), self.target_norm)


class SpanWriter(nn.Module):
    """Trainable write-side parts of B2: marker, ratio code, rep head, stop head."""

    def __init__(self, width: int, target_norm: float, marker_init: torch.Tensor | None = None):
        super().__init__()
        marker = torch.zeros(width) if marker_init is None else marker_init.detach().float().clone()
        self.marker = nn.Parameter(marker)
        self.ratio = RatioEmbedding(width)
        self.rep = RepHead(width, target_norm)
        self.stop = nn.Linear(width, 2)  # logits over (<|rep|>, <|/bg|>)

    def marker_embedding(self, factor: torch.Tensor) -> torch.Tensor:
        return self.marker + self.ratio(factor)


def span_targets(counts: list[int], device=None) -> torch.Tensor:
    """Stop labels for spans of ``counts`` reps: k positions of 0 (emit), then 1 (stop).

    Returned flat, in the order of the positions marker, r_1 ... r_k per span."""
    labels = []
    for k in counts:
        labels.extend([0] * k + [1])
    return torch.tensor(labels, dtype=torch.long, device=device)


class SpanGate:
    """Shared position weights for the write adapter: (B, T, 1), 1 inside write spans.

    ``None`` (the default, and outside ``active``) turns the adapter off entirely,
    so every forward that is not a write - ordinary text, reading spans - is the
    unmodified base decoder. Fractional weights elsewhere open the adapter
    gradually into a global one (B3 gate ramp)."""

    def __init__(self):
        self.mask: torch.Tensor | None = None

    def active(self, mask: torch.Tensor):
        gate = self

        class _Scope:
            def __enter__(self):
                gate.mask = mask
                return gate

            def __exit__(self, *exc):
                gate.mask = None
                return False

        return _Scope()


class SpanLoRA(nn.Module):
    """Low-rank delta added to one linear module's output at gated positions only."""

    def __init__(self, module: nn.Module, gate: SpanGate, rank: int, alpha: float):
        super().__init__()
        weight = module.base_layer.weight if hasattr(module, 'base_layer') else module.weight
        out_features, in_features = weight.shape
        self.gate, self.scale = gate, alpha / rank
        self.down = nn.Linear(in_features, rank, bias=False)
        self.up = nn.Linear(rank, out_features, bias=False)
        nn.init.kaiming_uniform_(self.down.weight, a=math.sqrt(5))
        nn.init.zeros_(self.up.weight)
        self.__dict__['target'] = module  # not a submodule: its weights are not adapter state
        self.handle = module.register_forward_hook(self._hook)

    def _hook(self, module, inputs, output):
        mask = self.gate.mask
        if mask is None:
            return output
        delta = self.up(self.down(inputs[0].to(self.down.weight.dtype))) * self.scale
        return output + (delta * mask.to(delta.dtype)).to(output.dtype)

    @torch.no_grad()
    def merge(self) -> None:
        """Fold the (fully open) delta into the target's weight and detach the hook."""
        module = self.target
        weight = module.base_layer.weight if hasattr(module, 'base_layer') else module.weight
        delta = (self.up.weight.float() @ self.down.weight.float()) * self.scale
        weight.copy_((weight.float() + delta).to(weight.dtype))
        self.handle.remove()


def attach_write_adapter(layers: nn.ModuleList, targets: tuple[str, ...], rank: int,
                         alpha: float, layer_ids=None) -> tuple[SpanGate, nn.ModuleDict]:
    """Attach span-gated LoRA to the named linear submodules of the given layers."""
    gate, adapters = SpanGate(), nn.ModuleDict()
    for index, layer in enumerate(layers):
        if layer_ids is not None and index not in layer_ids:
            continue
        for name, module in layer.named_modules():
            leaf = name.rsplit('.', 1)[-1]
            if leaf in targets and (isinstance(module, nn.Linear) or hasattr(module, 'base_layer')):
                key = f'{index}.{name}'.replace('.', '__')
                adapters[key] = SpanLoRA(module, gate, rank, alpha)
    if not adapters:
        raise ValueError('write adapter: no target linear modules found')
    return gate, adapters


def span_mask(starts: list[int], lengths: list[int], width: int, device=None) -> torch.Tensor:
    """(B, width, 1) mask of positions [start, start + length) per row."""
    pos = torch.arange(width, device=device)[None, :]
    start = torch.tensor(starts, device=device)[:, None]
    end = start + torch.tensor(lengths, device=device)[:, None]
    return ((pos >= start) & (pos < end)).unsqueeze(-1)


def fourier(x: torch.Tensor, frequencies: int = 8) -> torch.Tensor:
    """Features of values in [0, 1] (positions) or log-ratios: x, sin, cos at octave scales."""
    scales = 2.0 ** torch.arange(frequencies, device=x.device) * math.pi
    angles = x.unsqueeze(-1).float() * scales
    return torch.cat([x.unsqueeze(-1).float(), angles.sin(), angles.cos()], dim=-1)


class SpaceCodec(nn.Module):
    """Size-agnostic projection of a dense span (n reps) to a coarser space (m reps).

    Output i of m is a normalized, attention-weighted mix of the full-width source
    reps (plus a zero-initialized low-rank correction of the values and a
    query-conditioned delta), so pooling finer reps into coarser ones is the easy
    case and no narrow bottleneck carries content. Queries are generated from the
    normalized output position (i + 0.5) / m and the compression log2(n / m); keys
    see source content and normalized source position (j + 0.5) / n. Each round
    updates the queries from what they read. About 2M parameters at width 1024."""

    def __init__(self, width: int, target_norm: float, inner: int = 256, heads: int = 4,
                 rounds: int = 2, rank: int = 32, frequencies: int = 8):
        super().__init__()
        feats = 2 * frequencies + 1
        self.heads, self.inner, self.frequencies = heads, inner, frequencies
        self.target_norm = float(target_norm)
        self.query0 = nn.Sequential(nn.Linear(2 * feats, inner), nn.SiLU(), nn.Linear(inner, inner))
        self.key_content = nn.Sequential(nn.LayerNorm(width), nn.Linear(width, inner))
        self.key_position = nn.Linear(feats, inner)
        self.read_back = nn.Linear(width, inner)
        self.rounds = nn.ModuleList(
            nn.ModuleDict({'q': nn.Linear(inner, inner),
                           'mlp': nn.Sequential(nn.LayerNorm(inner), nn.Linear(inner, 2 * inner),
                                                nn.SiLU(), nn.Linear(2 * inner, inner))})
            for _ in range(rounds))
        self.value_down = nn.Linear(width, rank, bias=False)
        self.value_up = nn.Linear(rank, width, bias=False)
        self.delta = nn.Linear(inner, width)
        for layer in (self.value_up, self.delta):
            nn.init.zeros_(layer.weight)
        nn.init.zeros_(self.delta.bias)

    def forward(self, source: torch.Tensor, count: int) -> torch.Tensor:
        """``source`` (n, width) -> (count, width) in the decoder's input space."""
        n, device = source.shape[0], source.device
        x = source.float()
        out_pos = (torch.arange(count, device=device) + 0.5) / count
        src_pos = (torch.arange(n, device=device) + 0.5) / n
        ratio = torch.full((count,), math.log2(max(n, 1) / max(count, 1)) / 8, device=device)
        query = self.query0(torch.cat([fourier(out_pos, self.frequencies),
                                       fourier(ratio, self.frequencies)], dim=-1))
        keys = self.key_content(x) + self.key_position(fourier(src_pos, self.frequencies))
        values = x + self.value_up(self.value_down(x))
        head = self.inner // self.heads
        k = keys.view(n, self.heads, head).transpose(0, 1)
        for block in self.rounds:
            q = block['q'](query).view(count, self.heads, head).transpose(0, 1)
            weights = torch.softmax(q @ k.transpose(1, 2) / math.sqrt(head), dim=-1)
            mixed = (weights @ values.unsqueeze(0)).mean(0)          # (count, width)
            query = query + block['mlp'](query + self.read_back(mixed))
        return interface_rms(mixed + self.delta(query), self.target_norm)
